### ISSUE TITLE
タイトルを取得できない

### ISSUE THREAD

**Issue by keepoff07** [keepoff07/keepoff07.github.io#5]
![o](https://gyazo.com/e9ae5916cf2b13cebc0b5434286f83ae.jpg)
よくわからない

`Nuitter : おかずのタイトルを取得` - https://github.com/keepoff07/keepoff07.github.io/commit/967f9eb787f343348b99d97127d0505a3cee180e

![n](https://gyazo.com/3f1f9b892a32f4acfa4d3615cb6e81ee.png)

**Comment by 844196** [comment]
@keepoff07 だいたい原因判明
![2015-08-24_23-11-04](https://cloud.githubusercontent.com/assets/4990822/9442215/9d918fdc-4ab5-11e5-98a0-b434f5964abc.png)

`XMLHttpRequest`は自ドメイン（この場合<https://keepoff07.github.io/>以内かな？）を超えてドキュメントを取得する際は、対象のレスポンスヘッダで明示的にアクセスが許可されてなければいけないようです（CORSといいます）。また、許可されていても自ドメインが`https`からは無理そうです。

（試しに<http://keepoff07.github.io/nuitter/share>に<http://www.html5rocks.com/ja/>を打ち込み`おかずをシェア`を押してみてください。このサイトはCORSに対応しています。）

**Comment by keepoff07** [comment]
なるほど、ありがとうございます
