### ISSUE TITLE
コマンドブロックちゃんのライセンスについて

### ISSUE THREAD

**Issue by 844196** [keepoff07/keepoff07.github.io#9]
<http://keepoff07.github.io/cmd-chan/icons>下部には

> Copyright (C) 2015 CommandBlock-Chan

の表記があります。

表題の通り、コマンドブロックちゃんのライセンスを教えてください。

**Comment by keepoff07** [comment]
キャラクター原案者から私個人の利用許可は得ているのですが、
そこからの第三者への利用について聞いておりませんでした。
本件を踏まえライセンスをハッキリさせようと思います。

~~ぶっちゃけ一部へしか公開しないから適当に書いたなんて言えない~~

**Comment by keepoff07** [comment]
@844196 
<table>
<tr>
<td><img src="http://i.imgur.com/47yuJuQ.png"><br>
image by CommandBlockProject / <a href="http://creativecommons.org/licenses/by/4.0/deed.ja">CC BY 4.0</a><br>
<hr>＿＿|￣￣|_______？
</td>
<td>原画さんと相談したところ、<br>
<a href="http://creativecommons.org/licenses/by/4.0/deed.ja">クリエイティブ・コモンズ 表示 4.0 国際 ライセンス</a>で提供することになりました。<br>
詳しくは下記リンクをご覧ください。<br>
<a href="http://keepoff07.github.io/cmd-chan/index.html?page=about">http://keepoff07.github.io/cmd-chan/index.html?page=about</a><br>
<br>
また、キャラクターの名前が「コマンドブロックちゃん」→「コマブロちゃん」に、<br>
プロジェクトの名前が「CommandBlockProject」に決定しました。<br>
今後コマブロちゃんに関するIssuesを作成する場合は、<br>
「CommandBlockProject」のラベルを付けていただけると助かります。<br>
</td>
</tr>
</table>
affected commit: https://github.com/keepoff07/keepoff07.github.io/commit/dfc8a391ae55c64bee9c408253a38e0302c0e765

**Comment by 844196** [comment]
@keepoff07 

> CC 4.0-Attribution

了解です、お疲れ様です:+1:

> ＿＿|￣￣|_______？

＿＿|￣￣|_______



> 今後コマブロちゃんに関するIssuesを作成する場合は、
> 「CommandBlockProject」のラベルを付けていただけると助かります。

Ownerじゃないとラベル貼れないのん...

**Comment by keepoff07** [comment]
![cmd-chan](http://i.imgur.com/3jIgMC2.png)
